/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/apple_macbook_pro.glb --meta 
Author: Andrey 3D (https://sketchfab.com/Andrey3Ds)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/apple-macbook-pro-eddf60ccdaba497c9e256e64bd0946d9
Title: Apple MacBook Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apple_macbook_pro.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['macbookpro-material'].geometry} material={materials.macbookpro} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'macbookpro-material' }} />
    </group>
  )
}

useGLTF.preload('/apple_macbook_pro.glb')
